In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\dasar\OneDrive\Dokumen\innomatics\python_487\Machine_Learning\banana_quality_dataset.csv")

In [3]:
df.head()

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,1,Manzano,Colombia,1.88,Processing,2.11,Turning,16.83,3.53,21.44,146.92,2023-10-16,13.7,58.2,2440.5,183.6
1,2,Plantain,Guatemala,2.42,Processing,4.25,Ripe,16.73,4.09,26.11,160.48,2023-10-14,5.1,280.2,2374.6,109.8
2,3,Burro,Ecuador,3.57,Premium,6.24,Overripe,21.34,1.63,25.20,225.27,2023-09-08,17.7,1246.9,1191.5,147.7
3,4,Manzano,Ecuador,2.21,Processing,5.39,Ripe,16.75,3.31,13.08,137.80,2023-10-07,13.0,1150.2,2845.1,92.8
4,5,Red Dacca,Ecuador,2.35,Processing,5.84,Ripe,16.90,3.07,12.98,227.84,2023-10-02,4.8,526.0,2136.9,129.7

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sample_id           1000 non-null   int64
 1   variety             1000 non-null   object
 2   region              1000 non-null   object
 3   quality_score       1000 non-null   float64
 4   quality_category    1000 non-null   object
 5   ripeness_index      1000 non-null   float64
 6   ripeness_category   1000 non-null   object
 7   sugar_content_brix  1000 non-null   float64
 8   firmness_kgf        1000 non-null   float64
 9   length_cm           1000 non-null   float64
 10  weight_g            1000 non-null   float64
 11  harvest_date        1000 non-null   object
 12  tree_age_years      1000 non-null   float64
 13  altitude_m          1000 non-null   float64
 14  rainfall_mm         1000 non-null   float64
 15  soil_nitrogen_ppm   1000 non-null   float64
dtypes: float64(10), int64(1), object(5)
memory usage: 125.1+ KB

In [5]:
df.describe()

,sample_id,quality_score,ripeness_index,sugar_content_brix,firmness_kgf,length_cm,weight_g,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,2.465160,4.042170,18.516830,2.706840,19.882100,164.738930,10.879600,723.556700,1972.992800,104.391300
std,288.819436,0.540909,1.753211,2.034812,1.289252,5.736318,49.163073,5.215554,427.372855,564.467912,53.607794
min,1.000000,0.920000,1.020000,15.000000,0.500000,10.000000,81.050000,2.000000,0.400000,1000.500000,10.000000
25%,250.750000,2.090000,2.447500,16.827500,1.590000,14.902500,122.397500,6.300000,353.950000,1498.750000,60.150000
50%,500.500000,2.440000,4.110000,18.500000,2.680000,19.890000,163.365000,10.700000,726.000000,1957.400000,104.100000
75%,750.250000,2.850000,5.562500,20.312500,3.820000,24.800000,205.775000,15.600000,1071.725000,2431.800000,149.850000
max,1000.000000,3.890000,7.000000,21.980000,5.000000,29.950000,249.890000,20.000000,1498.400000,2992.000000,199.900000

In [6]:
df

,sample_id,variety,region,quality_score,quality_category,ripeness_index,ripeness_category,sugar_content_brix,firmness_kgf,length_cm,weight_g,harvest_date,tree_age_years,altitude_m,rainfall_mm,soil_nitrogen_ppm
0,1,Manzano,Colombia,1.88,Processing,2.11,Turning,16.83,3.53,21.44,146.92,2023-10-16,13.7,58.2,2440.5,183.6
1,2,Plantain,Guatemala,2.42,Processing,4.25,Ripe,16.73,4.09,26.11,160.48,2023-10-14,5.1,280.2,2374.6,109.8
2,3,Burro,Ecuador,3.57,Premium,6.24,Overripe,21.34,1.63,25.20,225.27,2023-09-08,17.7,1246.9,1191.5,147.7
3,4,Manzano,Ecuador,2.21,Processing,5.39,Ripe,16.75,3.31,13.08,137.80,2023-10-07,13.0,1150.2,2845.1,92.8
4,5,Red Dacca,Ecuador,2.35,Processing,5.84,Ripe,16.90,3.07,12.98,227.84,2023-10-02,4.8,526.0,2136.9,129.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Burro,Ecuador,3.50,Good,4.94,Ripe,21.06,2.49,27.95,196.35,2023-10-04,12.4,409.7,2029.9,173.0
996,997,Cavendish,Philippines,2.38,Processing,6.74,Overripe,16.10,2.00,12.39,165.55,2023-09-23,14.0,314.3,1330.7,180.5
997,998,Plantain,Ecuador,1.68,Processing,1.41,Green,17.17,2.28,16.56,210.08,2023-10-19,18.4,683.0,2955.4,189.9
998,999,Fehi,Guatemala,2.02,Processing,1.34,Green,17.03,2.88,26.31,162.50,2023-09-22,8.2,1362.7,1215.8,85.5
999,1000,Red Dacca,Ecuador,2.69,Good,2.69,Turning,21.10,1.23,21.95,105.39,2023-09-29,13.2,156.7,2863.9,51.3

In [7]:
df.drop(["sample_id","harvest_date"],axis = 1 , inplace = True)

In [8]:
y = df["quality_score"]
y

0      1.88
1      2.42
2      3.57
3      2.21
4      2.35
       ...
995    3.50
996    2.38
997    1.68
998    2.02
999    2.69
Name: quality_score, Length: 1000, dtype: float64

In [9]:
x = df.drop(["quality_score"],axis =1)

In [10]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   variety             1000 non-null   object
 1   region              1000 non-null   object
 2   quality_category    1000 non-null   object
 3   ripeness_index      1000 non-null   float64
 4   ripeness_category   1000 non-null   object
 5   sugar_content_brix  1000 non-null   float64
 6   firmness_kgf        1000 non-null   float64
 7   length_cm           1000 non-null   float64
 8   weight_g            1000 non-null   float64
 9   tree_age_years      1000 non-null   float64
 10  altitude_m          1000 non-null   float64
 11  rainfall_mm         1000 non-null   float64
 12  soil_nitrogen_ppm   1000 non-null   float64
dtypes: float64(9), object(4)
memory usage: 101.7+ KB

In [11]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OrdinalEncoder , StandardScaler
ct = ColumnTransformer(transformers = [('oe',OrdinalEncoder(),[0,1,2,4]),
                                       ('sc',StandardScaler(),[3,5,6,7,8,9,10,11,12,])])

In [12]:
x_transformed  = ct.fit_transform(x)
x_transformed

array([[ 5.        ,  1.        ,  2.        , ..., -1.55763199,
         0.82864078,  1.47829873],
       [ 6.        ,  4.        ,  2.        , ..., -1.03791932,
         0.71183524,  0.1009444 ],
       [ 1.        ,  3.        ,  1.        , ...,  1.2251718 ,
        -1.38516968,  0.8082849 ],
       ...,
       [ 6.        ,  3.        ,  2.        , ..., -0.09494518,
         1.7412837 ,  1.59587776],
       [ 3.        ,  4.        ,  2.        , ...,  1.49626516,
        -1.34209875, -0.35257471],
       [ 7.        ,  3.        ,  0.        , ..., -1.32703876,
         1.57910303, -0.99086087]])

In [13]:
x_transformed = pd.DataFrame(x_transformed , columns = x.columns)

In [14]:
from sklearn.feature_selection import mutual_info_regression
mf = mutual_info_regression(x_transformed, y)

In [15]:
mf = pd.Series(mf)
mf.index = x_transformed.columns
mf.sort_values(ascending = False)

quality_category      0.918699
ripeness_category     0.324784
sugar_content_brix    0.270723
ripeness_index        0.255715
length_cm             0.139107
firmness_kgf          0.042367
weight_g              0.032553
rainfall_mm           0.027273
altitude_m            0.023121
soil_nitrogen_ppm     0.018278
region                0.003905
variety               0.000608
tree_age_years        0.000000
dtype: float64

In [16]:
x.drop(["variety","region","tree_age_years"],axis = 1 , inplace = True)

In [17]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   quality_category    1000 non-null   object
 1   ripeness_index      1000 non-null   float64
 2   ripeness_category   1000 non-null   object
 3   sugar_content_brix  1000 non-null   float64
 4   firmness_kgf        1000 non-null   float64
 5   length_cm           1000 non-null   float64
 6   weight_g            1000 non-null   float64
 7   altitude_m          1000 non-null   float64
 8   rainfall_mm         1000 non-null   float64
 9   soil_nitrogen_ppm   1000 non-null   float64
dtypes: float64(8), object(2)
memory usage: 78.3+ KB

In [18]:
ct = ColumnTransformer(transformers = [('oe',OrdinalEncoder(),[0,2]),
                                      ('sc',StandardScaler(),[1,4,3,5,6,7,8,9])])

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2)

In [20]:
x_train_transform = ct.fit_transform(x_train)
x_train_tansform = pd.DataFrame(x_train_transform)

In [21]:
x_test_transform = ct.transform(x_test)
x_test_tansform = pd.DataFrame(x_test)

In [42]:
from sklearn.neighbors import KNeighborsRegressor
kn = KNeighborsRegressor(n_neighbors = 7,p=1)

In [43]:
kn.fit(x_train_transform,y_train)

KNeighborsRegressor(n_neighbors=7, p=1)

In [44]:
y_pred = kn.predict(x_test_transform)

In [45]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred) * 100
print(r2)

91.64442491085659

In [46]:
y_trian_pred = kn.predict(x_train_tansform)

In [47]:
r = r2_score(y_train,y_trian_pred)
r

0.9270130097533664

In [29]:
import warnings
warnings.filterwarnings('ignore')

In [41]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
kn = KNeighborsRegressor()

param_grid = {
    'n_neighbors': [3,5,7,9],
    'weights': ['uniform','distance'],
    'p': [1,2,3]
}

grid = GridSearchCV(estimator = kn , param_grid = param_grid , cv = 5 , scoring = 'r2' , verbose = 1)
grid.fit(x_train_transform,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(cv=5, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [3, 5, 7, 9], 'p': [1, 2, 3],
                         'weights': ['uniform', 'distance']},
             scoring='r2', verbose=1)

In [40]:
print("Best Parameters:",grid.best_params_)
print("Best CV Accuracy:",grid.best_score_)

Best Parameters: {'n_neighbors': 7, 'p': 1, 'weights': 'distance'}
Best CV Accuracy: 0.8986422581491293

In [51]:
from sklearn.model_selection import RandomizedSearchCV
random_search = RandomizedSearchCV(
    kn,
    param_distributions = param_grid,
    n_iter = 30,
    cv= 5,
    scoring = 'r2',
    verbose = 1 , n_jobs = -1
)
random_search.fit(x_train_transform , y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

RandomizedSearchCV(cv=5, estimator=KNeighborsRegressor(n_neighbors=7, p=1),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'n_neighbors': [3, 5, 7, 9],
                                        'p': [1, 2, 3],
                                        'weights': ['uniform', 'distance']},
                   scoring='r2', verbose=1)

In [52]:
print("Best Parameters:",random_search.best_params_)
print("Best CV Accuracy:",random_search.best_score_)

Best Parameters: {'weights': 'distance', 'p': 1, 'n_neighbors': 7}
Best CV Accuracy: 0.8986422581491293

In [54]:
from sklearn.model_selection import cross_val_score
score  = cross_val_score(kn,x_train_transform,y_train,cv = 5)
score

array([0.90320339, 0.88436644, 0.90811276, 0.90335217, 0.87605376])